### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by lexfrei**
- Updated dependencies
- Fixed Phyrexian lang code
- Added deprecation alert for Foil/NonFoil fields for cards
- Some missed fields added for card types
- Finishes added

### CODE REVIEW

**Comment by BlueMonday** [comment]
Thank you for fixing the language and updating to go 1.17! The review title says it is a WIP, let me know when its ready to go and I will merge it!

**Comment by lexfrei** [comment]
@BlueMonday I'm done for now. Feel free to merge.

I did some extra notes, but this is enough for me now.
Sorry for the no new tests.

**Comment by BlueMonday** [comment]
Thank you for helping keep things up to date!

**Comment by lexfrei** [comment]
@BlueMonday don't forget to create a new tag or move the existing one.

**Comment by BlueMonday** [comment]
> @BlueMonday don't forget to create a new tag or move the existing one.

Thank you for the reminder, I tagged v0.2.0.

**Pull request merged**
